language: ruby
rvm:
  - ruby-head
  - 2.1.0
  - 2.0.0
  - rbx-2.1.1
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-19mode

gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile

branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: ruby-head
